### ISSUE TITLE
Error using Suppressions Retrieve "Cannot convert null to 'bool'"

### ISSUE THREAD

**Issue by frarodnie** [darrencauthon/csharp-sparkpost#117]
Looks like there is an error using Suppressions.Retrieve("Email@dominio.com") method when the email is on the suppression list, throwing an error "Cannot convert null to 'bool' because it is a non-nullable value type" , if the email is not in the supression list works fine, everything was working ok one and a half moths ago, probably sparpork changed the data cooming back.

I'm using the library from NuGet package version 1.9.3,
by the way the NuGet package ZIP archive contains unsupported data structures.

Bellow a error trace:
at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SparkPost.Suppressions.ConvertResultsToAListOfSuppressions(Object results)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at SparkPost.Suppressions.<Retrieve>c__async2.MoveNext()

**Comment by darrencauthon** [comment]
I will take a look at this soon, thank you for reporting!

**Comment by darrencauthon** [comment]
There is a fix for this on 1.11.1, available on nuget now.  Thanks again for reporting!
